### ISSUE TITLE
Problems with Rec Opt Nat8

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/azle#1526]
Running this

```javascript
import { IDL } from '@dfinity/candid';
import { Principal } from '@dfinity/principal';

const recRecordFunc = IDL.Rec();
const recOpt = IDL.Rec();
recRecordFunc.fill(
    IDL.Record({ func: IDL.Func([], [IDL.Opt(IDL.Nat8)]), opt: recOpt })
);
recOpt.fill(IDL.Opt(IDL.Nat8));

const recRecordOpt = IDL.Rec();
const recOpt2 = IDL.Rec();
recOpt2.fill(IDL.Opt(IDL.Nat8));
recRecordOpt.fill(IDL.Record({ firstOpt: IDL.Opt(IDL.Nat8), opt: recOpt }));

const myRecRecordFunc = {
    _b14: [
        Principal.fromText(
            'bpyi5-2bzji-dsb2y-bav6a-jeig6-eakqa-ibawc-73crj-st4ac-berzm-mwy'
        ),
        ''
    ],
    _OR7IWcz8Oa1n: {
        _3: []
    }
};
const myRecRecordOpt = {
    _b14: [],
    _OR7IWcz8Oa1n: {
        _3: []
    }
};
const encodedRecRecordFunc = IDL.encode([recRecordFunc], [myRecRecordFunc]);
const encodedRecRecordOpt = IDL.encode([recRecordOpt], [myRecRecordOpt]);
IDL.decode([recRecordFunc], encodedRecRecordFunc);
IDL.decode([recRecordOpt], encodedRecRecordOpt);
console.log('FINISH');
```

Gives this error:
```
node_modules/@dfinity/candid/src/idl.ts:1624
        const err = new Error(e.message + '\n\n');
                    ^


Error: Record is missing key "opt".


    at <anonymous> (node_modules/@dfinity/candid/src/idl.ts:1624:21)
    at <anonymous> (node_modules/@dfinity/candid/src/idl.ts:50:27)
    at Array.map (<anonymous>)
    at zipWith (node_modules/@dfinity/candid/src/idl.ts:50:13)
    at Object.encode node_modules/@dfinity/candid/src/idl.ts:1620:8)
    at <anonymous> (test.ts:33:34)
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.14.0
```

**Comment by bdemann** [comment]
There are actually two different errors here. They are probably the same bug as each other and both of them are probably the same as https://github.com/demergent-labs/azle/issues/1513, or at least I hope so.

One error is with this set up
```javascript
import {
    Canister,
    query,
    Opt,
    None,
    Recursive,
    Func,
    int16,
    nat8,
    Record,
    nat16
} from 'azle';
import { DfinityPrincipal } from 'azle';

// #region Declarations
const _4b = Recursive(() =>
    Record({
        _b14: Func([], Opt(nat8), 'update'),
        _OR7IWcz8Oa1n: Record({
            _3: _e74Um0wqn06
        })
    })
);
const _e74Um0wqn06 = Recursive(() => Opt(nat8));
// #endregion Declarations

export default Canister({
    simpleQuery: query([], _4b, () => {
        return {
            _b14: [
                DfinityPrincipal.fromText(
                    'bpyi5-2bzji-dsb2y-bav6a-jeig6-eakqa-ibawc-73crj-st4ac-berzm-mwy'
                ),
                ''
            ],
            _OR7IWcz8Oa1n: {
                _3: None
            }
        };
    })
});
```
And that gets this error when run with the agent
```
Error: Not an option type
```
The other is very similar
```javascript
import {
    Canister,
    query,
    Opt,
    None,
    Recursive,
    Func,
    int16,
    nat8,
    Record,
    nat16
} from 'azle';
import { DfinityPrincipal } from 'azle';

// #region Declarations
const _4b = Recursive(() =>
    Record({
        _b14: Opt(nat8),
        _OR7IWcz8Oa1n: Record({
            _3: _e74Um0wqn06
        })
    })
);
const _e74Um0wqn06 = Recursive(() => Opt(nat8));
// #endregion Declarations

export default Canister({
    simpleQuery: query([], _4b, () => {
        return {
            _b14: None,
            _OR7IWcz8Oa1n: {
                _3: None
            }
        };
    })
});
```
But gives this error from the agent
```
Error: Call failed:
  Canister: bkyz2-fmaaa-aaaaa-qaaaq-cai
  Method: simpleQuery (query)
  "Status": "rejected"
  "Code": "CanisterError"
  "Message": "IC0503: Canister bkyz2-fmaaa-aaaaa-qaaaq-cai trapped explicitly: Panicked at 'called `Result::unwrap()` on an `Err` value: Uncaught Error: Missing type index for opt nat8\n    at indexOf (main.js:96683)\n    at encodeType (main.js:96803)\n    at <anonymous> (main.js)\n    at map (native)\n    at _buildTypeTableImpl (main.js:97371)\n    at buildTypeTable (main.js:96776)\n    at _buildTypeTableImpl (main.js:97598)\n    at buildTypeTable (main.js:96776)\n    at <anonymous> (main.js)\n    at forEach (native)\n    at encode2 (main.js:97818)\n    at encodeSingle (main.js:99078)\n    at encode3 (main.js:99062)\n    at executeMethod (main.js:99780)\n    at <anonymous> (main.js:99794)\n', canister/src/lib.rs:98:14"
```
I tried recreating those errors with this code
```
import { IDL } from '@dfinity/candid';
import { Principal } from '@dfinity/principal';

const recRecordFunc = IDL.Rec();
const recOpt = IDL.Rec();
recRecordFunc.fill(
    IDL.Record({ func: IDL.Func([], [IDL.Opt(IDL.Nat8)]), opt: recOpt })
);
recOpt.fill(IDL.Opt(IDL.Nat8));

const recRecordOpt = IDL.Rec();
const recOpt2 = IDL.Rec();
recOpt2.fill(IDL.Opt(IDL.Nat8));
recRecordOpt.fill(IDL.Record({ firstOpt: IDL.Opt(IDL.Nat8), opt: recOpt }));

const myRecRecordFunc = {
    _b14: [
        Principal.fromText(
            'bpyi5-2bzji-dsb2y-bav6a-jeig6-eakqa-ibawc-73crj-st4ac-berzm-mwy'
        ),
        ''
    ],
    _OR7IWcz8Oa1n: {
        _3: []
    }
};
const myRecRecordOpt = {
    _b14: [],
    _OR7IWcz8Oa1n: {
        _3: []
    }
};
const encodedRecRecordFunc = IDL.encode([recRecordFunc], [myRecRecordFunc]);
const encodedRecRecordOpt = IDL.encode([recRecordOpt], [myRecRecordOpt]);
IDL.decode([recRecordFunc], encodedRecRecordFunc);
IDL.decode([recRecordOpt], encodedRecRecordOpt);
console.log('FINISH');
```

Which should give either error depending on which IDL.decode line is positioned first.

The error I got when I ran this was very different than the errors mentioned above, I ran the canister code from the cli to see if the error was the same. It also looked very different from all of the errors I had seen up to this point. So instead of spending cycles on this error which will hopefully be resolved we https://github.com/demergent-labs/azle/issues/1513 I decided that I would leave my code here, and if this example is cleared up with 1513 is fixed then we can spend time refining and double checking this reproduction of this error.

**Comment by bdemann** [comment]
# Original Description

Here is the full thing including my attempt to isolate it to just IDL
```javascript
import { IDL } from '@dfinity/candid';
import { Principal } from '@dfinity/principal';
import {
    Canister,
    query,
    Opt,
    None,
    Recursive,
    Func,
    int16,
    nat8,
    Record,
    nat16
} from 'azle';
import * as deepEqual from 'fast-deep-equal';
// TODO solve the underlying principal problem https://github.com/demergent-labs/azle/issues/1443
// import { Principal as DfinityPrincipal } from '@dfinity/principal';
// import { Principal as DfinityPrincipal } from 'azle';
import { DfinityPrincipal } from 'azle';

// const recRecordFunc = IDL.Rec();
// const recOpt = IDL.Rec();
// recRecordFunc.fill(
//     IDL.Record({ func: IDL.Func([], [IDL.Opt(IDL.Nat8)]), opt: recOpt })
// );
// recOpt.fill(IDL.Opt(IDL.Nat8));

// const recRecordOpt = IDL.Rec();
// const recOpt2 = IDL.Rec();
// recOpt2.fill(IDL.Opt(IDL.Nat8));
// recRecordOpt.fill(IDL.Record({ firstOpt: IDL.Opt(IDL.Nat8), opt: recOpt }));

// const myRecRecordFunc = {
//     _b14: [
//         Principal.fromText(
//             'bpyi5-2bzji-dsb2y-bav6a-jeig6-eakqa-ibawc-73crj-st4ac-berzm-mwy'
//         ),
//         ''
//     ],
//     _OR7IWcz8Oa1n: {
//         _3: []
//     }
// };
// const myRecRecordOpt = {
//     _b14: [],
//     _OR7IWcz8Oa1n: {
//         _3: []
//     }
// };
// const encodedRecRecordFunc = IDL.encode([recRecordFunc], [myRecRecordFunc]);
// const encodedRecRecordOpt = IDL.encode([recRecordOpt], [myRecRecordOpt]);
// IDL.decode([recRecordFunc], encodedRecRecordFunc);
// IDL.decode([recRecordOpt], encodedRecRecordOpt);
// console.log('FINISH');

// #region Declarations
const _4b = Recursive(() =>
    Record({
        _b14: Func([], Opt(nat8), 'update'),
        // _b14: Opt(nat8),
        _OR7IWcz8Oa1n: Record({
            _3: _e74Um0wqn06
        })
    })
);
const _e74Um0wqn06 = Recursive(() => Opt(nat8));
// #endregion Declarations

export default Canister({
    simpleQuery: query([], _4b, () => {
        return {
            _b14: [
                DfinityPrincipal.fromText(
                    'bpyi5-2bzji-dsb2y-bav6a-jeig6-eakqa-ibawc-73crj-st4ac-berzm-mwy'
                ),
                ''
            ],
            // _b14: None,
            _OR7IWcz8Oa1n: {
                _3: None
            }
        };
    })
});
```
I'll break it out, but I wanted to save the full things just in case

**Comment by lastmjs** [comment]
This is still a problem as of `@dfinity/candid` `3.1.0`

**Comment by lastmjs** [comment]
Alright here's an update on this issue. I think there's still a problem.

First off, the following code seems to have some typos, I'm not sure it's useful. The property names and even the shape of the types are off. It might be worth trying to clean it up to see if there are issues, but it also might not be useful considering how much of it we'd have to change:

```typescript
import { IDL } from '@dfinity/candid';
import { Principal } from '@dfinity/principal';

const recRecordFunc = IDL.Rec();
const recOpt = IDL.Rec();
recRecordFunc.fill(
    IDL.Record({ func: IDL.Func([], [IDL.Opt(IDL.Nat8)]), opt: recOpt })
);
recOpt.fill(IDL.Opt(IDL.Nat8));

const recRecordOpt = IDL.Rec();
const recOpt2 = IDL.Rec();
recOpt2.fill(IDL.Opt(IDL.Nat8));
recRecordOpt.fill(IDL.Record({ firstOpt: IDL.Opt(IDL.Nat8), opt: recOpt }));

const myRecRecordFunc = {
    _b14: [
        Principal.fromText(
            'bpyi5-2bzji-dsb2y-bav6a-jeig6-eakqa-ibawc-73crj-st4ac-berzm-mwy'
        ),
        ''
    ],
    _OR7IWcz8Oa1n: {
        _3: []
    }
};
const myRecRecordOpt = {
    _b14: [],
    _OR7IWcz8Oa1n: {
        _3: []
    }
};
const encodedRecRecordFunc = IDL.encode([recRecordFunc], [myRecRecordFunc]);
const encodedRecRecordOpt = IDL.encode([recRecordOpt], [myRecRecordOpt]);
IDL.decode([recRecordFunc], encodedRecRecordFunc);
IDL.decode([recRecordOpt], encodedRecRecordOpt);
console.log('FINISH');
```

The following code I confirmed that there was some kind of error being thrown in earlier versions of azle and `@dfinity/*`. The code now runs without issue as of `@icp-sdk/core` `4.0.4`:

```typescript
import {
    Canister,
    query,
    Opt,
    None,
    Recursive,
    Func,
    int16,
    nat8,
    Record,
    nat16
} from 'azle';
import { DfinityPrincipal } from 'azle';

// #region Declarations
const _4b = Recursive(() =>
    Record({
        _b14: Func([], Opt(nat8), 'update'),
        _OR7IWcz8Oa1n: Record({
            _3: _e74Um0wqn06
        })
    })
);
const _e74Um0wqn06 = Recursive(() => Opt(nat8));
// #endregion Declarations

export default Canister({
    simpleQuery: query([], _4b, () => {
        return {
            _b14: [
                DfinityPrincipal.fromText(
                    'bpyi5-2bzji-dsb2y-bav6a-jeig6-eakqa-ibawc-73crj-st4ac-berzm-mwy'
                ),
                ''
            ],
            _OR7IWcz8Oa1n: {
                _3: None
            }
        };
    })
});
```

**Comment by lastmjs** [comment]
Based on my efforts so far the following is the only remaining issue (though I will keep looking into this issue to more fully explore it):

```typescript
import { IDL, query } from 'azle';

const _e74Um0wqn06 = IDL.Rec();
_e74Um0wqn06.fill(IDL.Opt(IDL.Nat8));
type _e74Um0wqn06 = [number] | [];

const _4b = IDL.Rec();
_4b.fill(
    IDL.Record({
        _b14: IDL.Opt(IDL.Nat8),
        _OR7IWcz8Oa1n: IDL.Record({
            _3: _e74Um0wqn06
        })
    })
);
type _4b = {
    _b14: [number] | [];
    _OR7IWcz8Oa1n: {
        _3: _e74Um0wqn06;
    };
};

export default class {
    @query([], _4b)
    simpleQuery(): _4b {
        return {
            _b14: [],
            _OR7IWcz8Oa1n: {
                _3: []
            }
        };
    }
}
```

Calling `simpleQuery` through the `dfx` CLI or through the JavaScript agent will give the same fundamental error: `Missing type index for opt nat8`

**Comment by lastmjs** [comment]
Once https://github.com/dfinity/icp-js-core/pull/1153 is merged and a new release of `@icp-sdk/core` is released, we should run the scripts manually from https://github.com/demergent-labs/azle/issues/1526#issuecomment-3336240715 and also re-enable the examples/stable/test/property/candid_rpc/recursive tests. If all tests pass across the entire repo after that, then we can close this issue.

**Comment by lastmjs** [comment]
As of `@icp-sdk/core` `4.0.5` the two scripts above work, the `recursive` property test works in stable and experimental mode, but we still have a handful of failing tests. I will need to look into them to see if they indicate issues with Azle or `@icp-sdk/core`.

**Comment by lastmjs** [comment]
Some fixes were made to Azle's internal tests and test framework and now the bulk of the tests have passed multiple times. This is good to go!
