### ISSUE TITLE
Tuple types

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#192]
I don't think there is any support for tuple types. See here: https://smartcontracts.org/docs/candid-guide/candid-types.html#type-record

- [x] Compile to Candid
- [x] AzleIntoJsValue
- [x] AzleFromJsValue
- [x] Derives
  - [ ] AzleIntoJsValue
    - [ ] Enum
    - [x] Struct
  - [ ] AzleTryFromJsValue
    - [ ] Enum
    - [x] Struct
- [x] Make sure records and variants can have tuples...tuples should be usable everywhere
- [x] inline tuples
- [x] Canister definitions
- [x] Stable storage

**Comment by cryptoisgood** [comment]
Running into this now

Trying type 
```
export type HeaderField = Record<string, string>;
``` 

expected candid:
```
type HeaderField = record { text; text; };
```

actual:

```
 be sure to add `../bin` to your PATH to be able to run the installed binaries
/home/daniel/.npm/_npx/22da3992a7cf1870/node_modules/azle/src/compiler/typescript_to_candid/generators/record.ts:317
    throw new Error(`Could not generate Candid record for type alias declaration: ${typeAliasDeclaration}`);
          ^
Error: Could not generate Candid record for type alias declaration: [object Object]
    at generateCandidRecord (/home/daniel/.npm/_npx/22da3992a7cf1870/node_modules/azle/src/compiler/typescript_to_candid/generators/record.ts:317:11)
    at /home/daniel/.npm/_npx/22da3992a7cf1870/node_modules/azle/src/compiler/typescript_to_candid/generators/record.ts:38:16
    at Array.map (<anonymous>)
    at generateCandidRecords (/home/daniel/.npm/_npx/22da3992a7cf1870/node_modules/azle/src/compiler/typescript_to_candid/generators/record.ts:37:45)
    at compileTypeScriptToCandid (/home/daniel/.npm/_npx/22da3992a7cf1870/node_modules/azle/src/compiler/typescript_to_candid/index.ts:46:30)
    at compileTypeScriptToRust (/home/daniel/.npm/_npx/22da3992a7cf1870/node_modules/azle/src/compiler/typescript_to_rust/index.ts:28:34)
    at azle (/home/daniel/.npm/_npx/22da3992a7cf1870/node_modules/azle/src/azle.ts:30:56)
    at Object.<anonymous> (/home/daniel/.npm/_npx/22da3992a7cf1870/node_modules/azle/src/azle.ts:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/daniel/.npm/_npx/22da3992a7cf1870/node_modules/ts-node/src/index.ts:1365:23)

```



Looks like a fairly straight forward fix? we just need to add to the generateCandidRecord in record.ts to support tsc.SyntaxKind.TypeReference I think?

**Comment by cryptoisgood** [comment]
we can't use strings as keys for variant either so this doesn't work. I don't know if you've ran into this yet

```
export type HeaderField = Variant<{
    "Accept"?: string
    "Accept-Encoding"?: string
    "Accept-language"?: string
    "Connection"?: string
    "Cookie"?:string
    "Host"?:string
    "Referer"?:string

    "content-type"?:string
}>;

```

**Comment by lastmjs** [comment]
That's correct, no strings as keys yet. Does it block you to do this?

```typescript
export type HeaderField = Variant<{
    Accept?: string
    AcceptEncoding?: string;
    AcceptLanguage?: string;
    Connection?: string;
    Cookie?: string;
    Host?: string;
    Referer?: string;
    contentType?: string;
}>;
```

**Comment by cryptoisgood** [comment]
Don't think the icp machine likes it :(

```
Replica Error (5): "IC0503: Canister r7inp-6aaaa-aaaaa-aaabq-cai trapped explicitly: Custom(Fail to decode argument 0 from table0 to variant {
  url : text;
  method : text;
  body : vec nat8;
  headers : vec variant {
    accept : text;
    host : text;
    content_type : text;
    upgrade_insecure_requests : text;
    sec_fetch_dest : text;
    sec_fetch_mode : text;
    accept_encoding : text;
    sec_fetch_site : text;
    sec_fetch_user : text;
    cookie : text;
    user_agent : text;
    referer : text;
    accept_language : text;
    connection : text;
  };
}

Caused by:
    0: input: 4449444c046c04efd6e40271e1edeb4a71a2f5ed880401c6a4a19806026d7b6d036c02007101710100_012f03474554000b04686f73740e3132372e302e302e313a383435330a757365722d6167656e744c4d6f7a696c6c612f352e3020285831313b205562756e74753b204c696e7578207838365f36343b2072763a39392e3029204765636b6f2f32303130303130312046697265666f782f39392e300661636365707455746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c696d6167652f617669662c696d6167652f776562702c2a2f2a3b713d302e380f6163636570742d6c616e67756167650e656e2d55532c656e3b713d302e350f6163636570742d656e636f64696e6711677a69702c206465666c6174652c2062720a636f6e6e656374696f6e0a6b6565702d616c69766519757067726164652d696e7365637572652d726571756573747301310e7365632d66657463682d6465737408646f63756d656e740e7365632d66657463682d6d6f6465086e617669676174650e7365632d66657463682d73697465046e6f6e650e7365632d66657463682d75736572023f31
       table: type table0 = record {
         5_843_823 : text;
         156_956_385 : text;
         1_092_319_906 : table1;
         1_661_489_734 : table2;
       }
       type table1 = vec nat8
       type table2 = vec table3
       type table3 = record { text; text }
       wire_type: table0, expect_type: variant {
         url : text;
         method : text;
         body : vec nat8;
         headers : vec variant {
           accept : text;
           host : text;
           content_type : text;
           upgrade_insecure_requests : text;
           sec_fetch_dest : text;
           sec_fetch_mode : text;
           accept_encoding : text;
           sec_fetch_site : text;
           sec_fetch_user : text;
           cookie : text;
           user_agent : text;
           referer : text;
           accept_language : text;
           connection : text;
         };
       }
    1: table0 is not a subtype of variant {
         url : text;
         method : text;
         body : vec nat8;
         headers : vec variant {
           accept : text;
           host : text;
           content_type : text;
           upgrade_insecure_requests : text;
           sec_fetch_dest : text;
           sec_fetch_mode : text;
           accept_encoding : text;
           sec_fetch_site : text;
           sec_fetch_user : text;
           cookie : text;
           user_agent : text;
           referer : text;
           accept_language : text;
           connection : text;
         };
       }
    2: record {
         5_843_823 : text;
         156_956_385 : text;
         1_092_319_906 : table1;
         1_661_489_734 : table2;
       } is not a subtype of variant {
         url : text;
         method : text;
         body : vec nat8;
         headers : vec variant {
           accept : text;
           host : text;
           content_type : text;
           upgrade_insecure_requests : text;
           sec_fetch_dest : text;
           sec_fetch_mode : text;
           accept_encoding : text;
           sec_fetch_site : text;
           sec_fetch_user : text;
           cookie : text;
           user_agent : text;
           referer : text;
           accept_language : text;
           connection : text;
         };
       })"

```

**Comment by lastmjs** [comment]
Actually we can just use the straight up `Tuple` type in TypeScript: https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple

Fits nicely with the @dfinity/agent JS representation. I've begun work on this

**Comment by lastmjs** [comment]
Live now: `npm install azle@0.2.2`
