### ISSUE TITLE
Error running "dfx deploy" from command line

### ISSUE THREAD

**Issue by zkung** [demergent-labs/azle#229]
## Operating environment
macOS v.10.15.4
```
rustc 1.42.0
dfx 0.9.3
typescript 4.4.3
```

## The following error occurred
```
error: failed to compile `didc v0.1.4 (https://github.com/dfinity/candid?rev=e7abc462fd54e72e3449999169c12e9f5209d091#e7abc462)`, intermediate artifacts can be found at `/var/folders/s2/s14lbmm90dj8mfllvxcq36_00000gn/T/cargo-install6UveWX`

Caused by:
  failed to download `fake v2.4.3`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/UserName/.cargo/registry/src/github.com-1ecc6299db9ec823/fake-2.4.3/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown
(node:10816) UnhandledPromiseRejectionWarning: Error: Command failed: cd target/azle && cargo install --git https://github.com/dfinity/candid --rev e7abc462fd54e72e3449999169c12e9f5209d091 didc --root ..
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at installRustDependencies (/Users/UserName/.npm/_npx/10816/lib/node_modules/azle/src/azle.ts:55:13)
    at azle (/Users/UserName/.npm/_npx/10816/lib/node_modules/azle/src/azle.ts:26:5)
    at Object.<anonymous> (/Users/UserName/.npm/_npx/10816/lib/node_modules/azle/src/azle.ts:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/UserName/.npm/_npx/10816/lib/node_modules/azle/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/UserName/.npm/_npx/10816/lib/node_modules/azle/node_modules/ts-node/src/index.ts:1368:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: The post-build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' with an embedded error: No such file or directory (os error 2)
```

**Comment by lastmjs** [comment]
Your `rustc 1.42.0` is quite a bit out of date. Try upgrading it with `rustup update` and see if that helps.

**Comment by zkung** [comment]
Thank you for your answer.
I am not very familiar with rust.
As the `rust` I was using was installed with `brew`, I couldn't do a valid version switch via the `rustup toolchain`, which caused the `dfx deploy` to fail.
I then ran `brew uninstall rust` to uninstall and reinstall `rust` on the official site.

I then ran `brew uninstall rust` and reinstalled `rust` on the official site.
Now it's running `azle example` successfully!
```
Final Size: 1.85 MiB (44.4% smaller)
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "ryjl3-tyaaa-aaaaa-aaaba-cai"
Installing code for canister query, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
Deployed canisters.
URLs:
  Candid:
    query: http://127.0.0.1:8000/?canisterId=ryjl3-tyaaa-aaaaa-aaaba-cai&id=rrkah-fqaaa-aaaaa-aaaaq-cai
```
dfx canister call
```
> dfx canister call query query
("This is a query function")
```

**Comment by lastmjs** [comment]
Great news!
