### ISSUE TITLE
Missing `_azle` prefix created apparent stable storage issues

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#347]
Here's the code:

```typescript
import {
    ic,
    Init,
    PreUpgrade,
    PostUpgrade,
    Heartbeat,
    Stable
} from 'azle';

type StableStorage = Stable<{
    message: string;
}>;

export function init(message: string): Init {
    ic.print(`init ${message}!`);
    ic.stableStorage<StableStorage>().message = message;
}

export function pre_upgrade(): PreUpgrade {
    ic.print(`pre_upgrade ${ic.stableStorage<StableStorage>().message}`);
}

export function post_upgrade(): PostUpgrade {
    ic.print(`post_upgrade ${ic.stableStorage<StableStorage>().message}`);
}

export function heartbeat(): Heartbeat {
    ic.print(`heartbeat ${ic.stableStorage<StableStorage>().message}`);
}
```

Here's the error:

```typescript
error[E0382]: use of moved value: `message`
   --> src/src/lib.rs:825:29
    |
696 |             let (message,): (String,) = ic_cdk::storage::stable_restore().unwrap();
    |                  ------- move occurs because `message` has type `std::string::String`, which does not implement the `Copy` trait
697 | 
698 |             let message_js_value = message.azle_into_js_value(boa_context);
    |                                            ------------------------------- `message` moved due to this method call
...
825 |                             message.azle_into_js_value(boa_context)
    |                             ^^^^^^^ value used here after move
    |
note: this function takes ownership of the receiver `self`, which moves `message`
   --> src/src/lib.rs:43:35
    |
43  |             fn azle_into_js_value(self, context: &mut boa_engine::Context) -> boa_engine::JsValue;
    |                                   ^^^^

For more information about this error, try `rustc --explain E0382`.
error: could not compile `supernova` due to previous error
Error: Command failed: cd target/azle && CARGO_TARGET_DIR=.. cargo build --target wasm32-unknown-unknown --package supernova --release
    at checkExecSyncError (node:child_process:817:11)
    at execSync (node:child_process:888:15)
    at compileRustCode (/home/lastmjs/development/test-projects/supernova/node_modules/azle/src/azle.ts:98:13)
    at azle (/home/lastmjs/development/test-projects/supernova/node_modules/azle/src/azle.ts:42:5)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 101,
  signal: null,
  output: [ null, null, null ],
  pid: 26859,
  stdout: null,
  stderr: null
}
Error: The build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' with an embedded error: The custom tool failed.
```

**Comment by lastmjs** [comment]
I think it's because I used the same variable name as the param to init/post_upgrade and as the stable storage variable...we need to be careful of these situations and prevent them if helpful

**Comment by lastmjs** [comment]
Make sure to document this thoroughly

**Comment by lastmjs** [comment]
This is just one example of running into this problem, we should find a general solution to this.

**Comment by dansteren** [comment]
This whole issue stemmed from us forgetting to add a `_azle` prefix on some of our methods. We just need to be vigilant to not let that happen. Beyond that there's no concrete work to add to this ticket. Closing for now.
