### ISSUE TITLE
Errors building an azle canister

### ISSUE THREAD

**Issue by domwoe** [demergent-labs/azle#711]
I tried to follow the steps in the readme (except naming) and end up with the following error when trying to build the canister:

```
azle_test dfx build azle_test        
Building canisters...
Executing 'npx azle azle_test'
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
    Updating git repository `https://github.com/dfinity/candid`
  Installing didc v0.1.4 (https://github.com/dfinity/candid?rev=5d3c7c35da652d145171bc071ac11c63d73bf803#5d3c7c35)
    Updating crates.io index
   Compiling proc-macro2 v1.0.46
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.4
   Compiling syn v1.0.101
   Compiling libc v0.2.134
   Compiling autocfg v1.1.0
   Compiling memchr v2.5.0
   Compiling thiserror v1.0.37
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling log v0.4.17
   Compiling once_cell v1.15.0
   Compiling serde_derive v1.0.145
   Compiling serde v1.0.145
   Compiling either v1.8.0
   Compiling hashbrown v0.12.3
   Compiling unicode-segmentation v1.10.0
   Compiling typenum v1.15.0
   Compiling ucd-trie v0.1.5
   Compiling minimal-lexical v0.2.1
   Compiling parking_lot_core v0.9.3
   Compiling unicode-width v0.1.10
   Compiling regex-syntax v0.6.27
   Compiling tinyvec_macros v0.1.0
   Compiling crunchy v0.2.2
   Compiling typed-arena v2.0.1
   Compiling arrayvec v0.5.2
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.9.0
   Compiling siphasher v0.3.10
   Compiling tiny-keccak v2.0.2
   Compiling precomputed-hash v0.1.1
   Compiling new_debug_unreachable v1.0.4
   Compiling lazy_static v1.4.0
   Compiling unicode-bidi v0.3.8
   Compiling bit-vec v0.6.3
   Compiling percent-encoding v2.2.0
   Compiling fixedbitset v0.4.2
   Compiling opaque-debug v0.3.0
   Compiling half v1.8.2
   Compiling stable_deref_trait v1.2.0
   Compiling doc-comment v0.3.3
   Compiling hex v0.4.3
   Compiling rustversion v1.0.9
   Compiling ppv-lite86 v0.2.16
   Compiling diff v0.1.13
   Compiling unicode-xid v0.2.4
   Compiling pico-args v0.4.2
   Compiling crc32fast v1.3.2
   Compiling anyhow v1.0.65
   Compiling beef v0.5.2
   Compiling fnv v1.0.7
   Compiling termcolor v1.1.3
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling base32 v0.4.0
   Compiling ansi_term v0.12.1
   Compiling bitflags v1.3.2
   Compiling leb128 v0.2.5
   Compiling humantime v2.1.0
   Compiling byteorder v1.4.3
   Compiling paste v1.0.9
   Compiling arbitrary v1.1.6
error[E0658]: use of unstable library feature 'array_from_fn'
   --> /Users/domwoe/.cargo/registry/src/github.com-1ecc6299db9ec823/arbitrary-1.1.6/src/lib.rs:655:36
    |
655 |         crate::size_hint::and_all(&array::from_fn::<_, N, _>(|_| {
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0747]: constant provided when a type was expected
   --> /Users/domwoe/.cargo/registry/src/github.com-1ecc6299db9ec823/arbitrary-1.1.6/src/lib.rs:655:56
    |
655 |         crate::size_hint::and_all(&array::from_fn::<_, N, _>(|_| {
    |                                                        ^

   Compiling pretty-hex v0.2.1
Some errors have detailed explanations: E0658, E0747.
For more information about an error, try `rustc --explain E0658`.
error: could not compile `arbitrary` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `didc v0.1.4 (https://github.com/dfinity/candid?rev=5d3c7c35da652d145171bc071ac11c63d73bf803#5d3c7c35)`, intermediate artifacts can be found at `/var/folders/km/ffy3rlpj72s67k8fb8l3tsmw0000gn/T/cargo-installa2Rd0v`
Error: Command failed: cd target/azle && cargo install --git https://github.com/dfinity/candid --rev 5d3c7c35da652d145171bc071ac11c63d73bf803 didc --root ..
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at installRustDependencies (/Users/domwoe/Dev/learn/azle_test/node_modules/azle/src/azle.ts:48:13)
    at azle (/Users/domwoe/Dev/learn/azle_test/node_modules/azle/src/azle.ts:23:5)
    at Object.<anonymous> (/Users/domwoe/Dev/learn/azle_test/node_modules/azle/src/azle.ts:12:1)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Module.m._compile (/Users/domwoe/Dev/learn/azle_test/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/domwoe/Dev/learn/azle_test/node_modules/ts-node/src/index.ts:1368:12) {
  status: 101,
  signal: null,
  output: [ null, null, null ],
  pid: 15021,
  stdout: null,
  stderr: null
}
Error: Failed while trying to build all canisters.
Caused by: Failed while trying to build all canisters.
  The build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' (azle_test) with an embedded error: Failed to build custom canister azle_test.: Failed to run npx azle azle_test.: The custom tool failed.
```

**Comment by lastmjs** [comment]
What version of Rust do you have installed? I would first try making sure it's up to date, `rustup update` I believe is the command if you already have Rust installed

**Comment by domwoe** [comment]
Indeed! Had `rustc 1.62.0 (a8314ef7d 2022-06-27)` and with `1.64.0` it compiles.

**Comment by lastmjs** [comment]
Hopefully soon we'll be able to ship prebuilt binaries to get rid of the need and complications arising from installing Rust
