### ISSUE TITLE
Nice errors for invalid Records and Variants

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#964]
If a Record or a Variant is declared but isn't valid (for example it has dynamic keys), we need to present a nice descriptive error to the user.

This is the error that occurred for someone.

Code:

```typescript
import { 
    ic,
    Opt,
    Principal,
    $init,
    $update,
    Record,
    int32,
    nat64
} from 'azle';

let owner: Opt<Principal> = null;

export type Player = {
    owner: string;
    username: string;
};

export type State = Record<{
    players: {
        [key: string]: Player;
    };
}>;

// global state of players
let state : State = {
    players: {}
};

// init call
$init;
export function init() {
    ic.print ("init");    
    owner = ic.caller();
}

type LoginResult = Record<{
//    players: Player[];
    msg: string;
}>;

$update;
export function login (): LoginResult 
{
    const caller = ic.caller().toString ();

    if (state.players[caller] === undefined) {
        state.players[caller] = {
            owner: caller,
            username: "",
        };
    }

    let players : Player[] = Object.entries (state.players).map ((player) => {
        return {
                owner: player[1].owner,
                username: player[1].username,
            }
        });

    return {
//        players: players,
        msg: caller
    }
}
```

Notice that State should not be a Record. Here is the error:

```
Executing 'npx azle demo'
Error: Command failed: "/home/redacted/projects/demo/node_modules/azle/install_rust_dependencies.sh" 0.13.2 1.66.0
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at azle (/home/redacted/projects/demo/node_modules/azle/src/azle.ts:48:13)
    at Object.<anonymous> (/home/redacted/projects/demo/node_modules/azle/src/azle.ts:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Module.m._compile (/home/redacted/projects/demo/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Object.require.extensions.<computed> [as .ts] (/home/redacted/projects/demo/node_modules/ts-node/src/index.ts:1368:12)
    at Module.load (node:internal/modules/cjs/loader:1069:32) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7518,
  stdout: null,
  stderr: null
}
Error: Failed while trying to build all canisters.
```

**Comment by bdemann** [comment]
Jordan and I looked through this issues and it's not actually an issues, the syntax that was thought problematic doesn't actually do anything in typescript
